feat: add app zooming
MrTanoshii/rusty-autoclicker pull request #39
Opened 2022-12-16 12:45 UTC by nozwock

- Zoom in with `ctrl`+`=`
- Zoom out with `ctrl`+`-`

See if you'd like to merge this or not.

2022-12-27 23:21 UTC, MrTanoshii requested changes
Sorry for the late review

There are a few things that need changing purely because of changes to `eframe` and `egui`.
The changes to `app.rs` itself are 100% fine.

1. The minimum supported rust version in `Cargo.toml` should be changed bumped to `1.65` (as required by [`egui`](https://github.com/emilk/egui/blob/master/crates/eframe/CHANGELOG.md))
2. The default text size is now bigger due to https://github.com/emilk/egui/pull/2069 . Setting the font size to `12.0f32` works nicely https://github.com/MrTanoshii/rusty-autoclicker/blob/59ecdf1e818985aa744a7020227c2452412d4f2d/src/app.rs#L171

Merry Christmas and Happy New Year

2022-12-31 09:10 UTC, nozwock commented
> There are a few things that need changing purely because of changes to `eframe` and `egui`. 

Done

> Merry Christmas and Happy New Year

Happy New Year to you too.

2022-12-31 13:50 UTC, MrTanoshii approved these changes

2022-12-31 13:50 UTC, merged

2022-12-31 13:50 UTC, MrTanoshii commented
Thank you!